### ISSUE TITLE
Hi, do you meet the problem "num_pred=0" ?

### ISSUE THREAD

**Issue by deepmeng** [philip-huang/PIXOR#1]
Hi, man, I try your method and I often meet the problem "num_pred=0" in function "compute_ap", and this problem always leads to training process interrupt. Do you meet the same problem?

**Comment by philip-huang** [comment]
This is an indicator that your trained network is not making any positive prediction in inference mode.

**Comment by azamshoaib** [comment]
@deepmeng @philip-huang Hi I have also encountered the same issue, how do you resolve this.

**Comment by HenryJunW** [comment]
Same problem, any advice? Thanks.
