### ISSUE TITLE
Here is a Wechat group for discussing the lidar-based perception technologies. Welcome to join us.

### ISSUE THREAD

**Issue by deepmeng** [philip-huang/PIXOR#20]
![image](https://user-images.githubusercontent.com/8176780/70885516-0398c600-2014-11ea-83dc-c1419d19b611.png)

@yanghuan478 @czha5168 sorry for the lately update

**Comment by yanghuan478** [comment]
how can i join with you

**Comment by czha5168** [comment]
Hi Meng, Willing to join. Could you please leave your wechat id. Thanks!

**Comment by yanghuan478** [comment]
yanghuan102511

发自我的iPhone


------------------ Original ------------------

**Comment by deepmeng** [comment]
![image](https://user-images.githubusercontent.com/8176780/70885734-acdfbc00-2014-11ea-8fa1-ce430cb470e7.png)
@czha5168 @yanghuan478

**Comment by czha5168** [comment]
Many thanks!

**Comment by imdsafi09** [comment]
QR CODE is expired how can join

**Comment by deepmeng** [comment]
![image](https://user-images.githubusercontent.com/8176780/86899230-55ce3f80-c13c-11ea-9e9b-267be5e7af99.png)

@imdsafi09

**Comment by imdsafi09** [comment]
@deepmeng  thanks

**Comment by gkd2020** [comment]
Hi，QR code expired, how can I join wechat group

**Comment by deepmeng** [comment]
![image](https://user-images.githubusercontent.com/8176780/92344371-e0113080-f0f8-11ea-871e-76ac896a9bb6.png)

@gkd2020
