### ISSUE TITLE
Thanks for sharing the code, but I recommend the new readers to carefully make decision on using this repo.

### ISSUE THREAD

**Issue by YuanYunshuang** [philip-huang/PIXOR#30]

**Comment by YuanYunshuang** [comment]
Since I found many errors in this version of re-implementation. It took me way much time on debugging this repo than just re-writing everything myself.

**Comment by s0966066980** [comment]
did you remember how to train this project?

**Comment by Petros626** [comment]
@YuanYunshuang you're a man of honor.
