### ISSUE TITLE
How to train on kitti dataset?

### ISSUE THREAD

**Issue by vvanurag** [philip-huang/PIXOR#5]
Hi.
I downloaded synced+rectified 2011_09_26_drive_0005 dataset along with calibration file from
http://www.cvlibs.net/datasets/kitti/raw_data.php

Call me noob but I am unable to train on kitti dataset. Instruction says run
$: python srcs/main.py train (--name=$exp_name$)

But what should exp_name be for the above Kitti dataset be?

**Comment by philip-huang** [comment]
HI, I think you are downloading the raw kitti dataset. You need to download the KITTI 3D object detection dataset. 
[CLICK HERE](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d)
