### ISSUE TITLE
Where is anchor concept? What about IOU caculation in detecting vehcles?

### ISSUE THREAD

**Issue by ghost** [philip-huang/PIXOR#9]
Hi,

I didn't found any concept of anchor in detecting vehicles and also IOU calculation and NMS threshold. Can you pls give better insight?

**Comment by philip-huang** [comment]
Hi,

The original PIXOR paper did not used pre-defined anchors (which are commonly seen in object detection works) to generate bounding box for cars in the Birds' Eye View. Instead, the raw position/size/orientation of the bounding box is directly regressed with respect to their means across the training set.

After you obtain the bounding box from the neural network, the rest of the process(IOU calculation, NMS) are similar to standard object detection works. There are many well-written Medium articles that explains these concepts really well.

Thanks.
Philip

**Comment by chowkamlee81** [comment]
thanks got your views. Closing issue
